### ISSUE TITLE
Update to babel 6

### ISSUE THREAD

**Issue by jayseeg** [jagrem/babel-resolve-relative-module#1]
Any plans to update to support babel 6?

**Comment by jagrem** [comment]
I am planning to support babel 6. Have not looked at what's involved yet, so no ETA on that, however it will be in the next release. Will also try to maintain backwards compatibility where possible.

**Comment by jayseeg** [comment]
Excellent, looking forward to it!

**Comment by jagrem** [comment]
Should now be compatible with Babel 6 in [version 1.0.0](https://github.com/jagrem/babel-resolve-relative-module/releases/tag/1.0.0)

**Comment by jayseeg** [comment]
awesome!
